---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - sensors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflows.jettisonproj.io
  resources:
  - flows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflows.jettisonproj.io
  resources:
  - flows/finalizers
  verbs:
  - update
- apiGroups:
  - workflows.jettisonproj.io
  resources:
  - flows/status
  verbs:
  - get
  - patch
  - update
